# Generated by Django 2.1.7 on 2019-03-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=100, verbose_name='Acerca de mi'),
        ),
    ]
